#!/usr/bin/env python3
"""Transfer reviewed CIE reference CSVs into C# constants. No network access."""
import argparse
import csv
import hashlib
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TABLES = [
    ("observers/CIE_xyz_1931_2deg", 360, 830, [("X2", 1), ("Y2", 2), ("Z2", 3)]),
    ("observers/CIE_xyz_1964_10deg", 360, 830, [("X10", 1), ("Y10", 2), ("Z10", 3)]),
    ("illuminants/CIE_std_illum_A_1nm", 300, 830, [("A", 1)]),
    ("illuminants/CIE_std_illum_D65", 300, 830, [("D65", 1)]),
    ("illuminants/CIE_illum_FLs_1nm", 380, 780, [("FL2", 2), ("FL7", 7), ("FL11", 11), ("FL12", 12)]),
]


def generate():
    output = [
        "// <auto-generated> Generated by tools/generate_cie_data.py; do not edit manually.",
        "// CIE numerical data: CC BY-SA 4.0. Attribution and modifications: CIE-DATA-NOTICE.md.",
        "// Original CSVs and source/update metadata are archived under reference/.",
        "// </auto-generated>",
        "namespace ChromaticityDotNet.Model", "{", "    internal static class CieReferenceData", "    {",
    ]
    for name, start, end, columns in TABLES:
        path = ROOT / "reference" / (name + ".csv")
        manifest = json.loads(path.with_suffix(".json").read_text(encoding="utf-8"))
        if hashlib.sha256(path.read_bytes()).hexdigest() != manifest["csvSha256"]:
            raise ValueError("Reference checksum mismatch: " + name)
        if any(not c["matches"] for c in manifest["officialChecksumValidation"]):
            raise ValueError("Unverified official checksum: " + name)
        rows = [r for r in csv.reader(path.read_text(encoding="utf-8-sig").splitlines()) if r]
        if [int(r[0]) for r in rows] != list(range(start, end + 1)):
            raise ValueError("Expected complete 1 nm grid: " + name)
        output.append("        // " + manifest["sourcePage"])
        output.append("        // CSV SHA-256: " + manifest["csvSha256"])
        for field, column in columns:
            values = []
            for row in rows:
                raw = row[column].strip()
                value = float(raw)
                if field == "Z10" and int(row[0]) >= 560 and math.isnan(value):
                    raw = "0"  # CIE 1964 z-bar undefined tail, zero for computation only.
                elif not math.isfinite(value) or value < 0:
                    raise ValueError(f"Unexpected sample {name}: {row}")
                values.append(raw + "d")
            output.extend(["        internal static readonly double[] " + field + " =", "        {"])
            for i in range(0, len(values), 6):
                output.append("            " + ", ".join(values[i:i + 6]) + ",")
            output.extend(["        };", ""])
    output.extend(["    }", "}", ""])
    return "\n".join(output)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if generated code differs; write nothing")
    args = parser.parse_args()
    content = generate()
    destination = ROOT / "Model" / "CieReferenceData.g.cs"
    if args.check:
        if not destination.exists() or destination.read_text(encoding="utf-8") != content:
            raise SystemExit("CieReferenceData.g.cs needs regeneration.")
        print("Generated CIE constants match the reference archive.")
    else:
        destination.write_text(content, encoding="utf-8")
        print("Generated " + str(destination.relative_to(ROOT)))
